// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	interests "weatherit/usecases/interests"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Find provides a mock function with given fields: ctx
func (_m *Repository) Find(ctx context.Context) ([]interests.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []interests.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []interests.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interests.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
