// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	activities "weatherit/usecases/activities"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FindActivitiesByInterest provides a mock function with given fields: ctx, interestIds, isOut
func (_m *Repository) FindActivitiesByInterest(ctx context.Context, interestIds []int, isOut bool) []activities.Domain {
	ret := _m.Called(ctx, interestIds, isOut)

	var r0 []activities.Domain
	if rf, ok := ret.Get(0).(func(context.Context, []int, bool) []activities.Domain); ok {
		r0 = rf(ctx, interestIds, isOut)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]activities.Domain)
		}
	}

	return r0
}

// FindActivitiesInOut provides a mock function with given fields: ctx, isOut
func (_m *Repository) FindActivitiesInOut(ctx context.Context, isOut bool) []activities.Domain {
	ret := _m.Called(ctx, isOut)

	var r0 []activities.Domain
	if rf, ok := ret.Get(0).(func(context.Context, bool) []activities.Domain); ok {
		r0 = rf(ctx, isOut)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]activities.Domain)
		}
	}

	return r0
}
