// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	user_interests "weatherit/usecases/user_interests"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FindUserInterest provides a mock function with given fields: ctx, userId
func (_m *Repository) FindUserInterest(ctx context.Context, userId int) []user_interests.Domain {
	ret := _m.Called(ctx, userId)

	var r0 []user_interests.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) []user_interests.Domain); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user_interests.Domain)
		}
	}

	return r0
}

// Store provides a mock function with given fields: ctx, userInterests
func (_m *Repository) Store(ctx context.Context, userInterests []user_interests.Domain) error {
	ret := _m.Called(ctx, userInterests)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []user_interests.Domain) error); ok {
		r0 = rf(ctx, userInterests)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
