// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	weatherforecast "weatherit/usecases/weatherforecast"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetCurrentForecast provides a mock function with given fields: lat, long
func (_m *Repository) GetCurrentForecast(lat float64, long float64) weatherforecast.Domain {
	ret := _m.Called(lat, long)

	var r0 weatherforecast.Domain
	if rf, ok := ret.Get(0).(func(float64, float64) weatherforecast.Domain); ok {
		r0 = rf(lat, long)
	} else {
		r0 = ret.Get(0).(weatherforecast.Domain)
	}

	return r0
}

// GetTargetDTForecast provides a mock function with given fields: lat, long, dt1, dt2, mode
func (_m *Repository) GetTargetDTForecast(lat float64, long float64, dt1 int64, dt2 int64, mode string) weatherforecast.Domain {
	ret := _m.Called(lat, long, dt1, dt2, mode)

	var r0 weatherforecast.Domain
	if rf, ok := ret.Get(0).(func(float64, float64, int64, int64, string) weatherforecast.Domain); ok {
		r0 = rf(lat, long, dt1, dt2, mode)
	} else {
		r0 = ret.Get(0).(weatherforecast.Domain)
	}

	return r0
}
